openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 191 characters.'
                  example: ankunding.madison@example.org
                password:
                  type: string
                  description: ''
                  example: unde
              required:
                - email
                - password
      security: []
  /api/logout:
    post:
      summary: ''
      operationId: postApiLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/employees:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store the specified resource.'
      operationId: storeTheSpecifiedResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: ''
                  example: 10
                email:
                  type: string
                  description: ''
                  example: ebba.stokes@example.com
                username:
                  type: string
                  description: ''
                  example: praesentium
                first_name:
                  type: string
                  description: 'Must be at least 2 characters. Must not be greater than 120 characters.'
                  example: fckywiafvpk
                last_name:
                  type: string
                  description: 'Must be at least 2 characters. Must not be greater than 120 characters.'
                  example: gmauytukqqecitcyliewjn
                middle_initial:
                  type: string
                  description: 'Must be 1 character.'
                  example: i
                gender:
                  type: string
                  description: ''
                  example: M
                  enum:
                    - M
                    - F
                zip_code_id:
                  type: string
                  description: ''
                  example: molestiae
                prefix_id:
                  type: string
                  description: ''
                  example: nesciunt
                phone_number:
                  type: string
                  description: 'Must match the regex /^(\+\d{1,3}[- ]?)?\d{10}$/.'
                  example: '7692732814'
                place_name:
                  type: string
                  description: 'Must be at least 2 characters. Must not be greater than 225 characters.'
                  example: jzrrjiagaw
                age_in_years:
                  type: number
                  description: ''
                  example: 237224.1
                age_in_company_in_years:
                  type: number
                  description: ''
                  example: 453192112.50201
                date_of_birth:
                  type: string
                  description: 'Must be a valid date in the format <code>Y-m-d</code>.'
                  example: '2023-10-04'
                date_of_joining:
                  type: string
                  description: 'Must be a valid date in the format <code>Y-m-d</code>.'
                  example: '2023-10-04'
                time_of_birth:
                  type: string
                  description: 'Must be a valid date in the format <code>H:i:s</code>.'
                  example: '11:41:14'
              required:
                - email
                - username
                - first_name
                - last_name
                - middle_initial
                - gender
                - zip_code_id
                - prefix_id
                - phone_number
                - place_name
                - age_in_years
                - age_in_company_in_years
                - date_of_birth
                - date_of_joining
                - time_of_birth
      security: []
  '/api/employees/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified resource.'
      operationId: updateTheSpecifiedResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 191 characters.'
                  example: zleffler@example.net
                username:
                  type: string
                  description: ''
                  example: ut
                first_name:
                  type: string
                  description: 'Must be at least 2 characters. Must not be greater than 120 characters.'
                  example: dzhwtv
                last_name:
                  type: string
                  description: 'Must be at least 2 characters. Must not be greater than 120 characters.'
                  example: oupaval
                middle_initial:
                  type: string
                  description: 'Must be 1 character.'
                  example: g
                gender:
                  type: string
                  description: ''
                  example: F
                  enum:
                    - M
                    - F
                zip_code_id:
                  type: string
                  description: ''
                  example: null
                prefix_id:
                  type: string
                  description: ''
                  example: null
                phone_number:
                  type: string
                  description: 'Must match the regex /^(\+\d{1,3}[- ]?)?\d{10}$/.'
                  example: '+06115683698'
                place_name:
                  type: string
                  description: 'Must be at least 2 characters. Must not be greater than 225 characters.'
                  example: mjkymtqdpjbyp
                age_in_years:
                  type: number
                  description: ''
                  example: 221.56230176
                age_in_company_in_years:
                  type: number
                  description: ''
                  example: 166.1
                date_of_birth:
                  type: string
                  description: 'Must be a valid date in the format <code>Y-m-d</code>.'
                  example: '2023-10-04'
                date_of_joining:
                  type: string
                  description: 'Must be a valid date in the format <code>Y-m-d</code>.'
                  example: '2023-10-04'
                time_of_birth:
                  type: string
                  description: 'Must be a valid date in the format <code>H:i:s</code>.'
                  example: '11:41:14'
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the employee.'
        example: 198429
        required: true
        schema:
          type: integer
  /api/employees/import:
    post:
      summary: 'Imports employee data from a file.'
      operationId: importsEmployeeDataFromAFile
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: 'Must be a file.'
              required:
                - file
      security: []
  /api/regions:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store the specified resource.'
      operationId: storeTheSpecifiedResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: et
              required:
                - name
      security: []
  '/api/regions/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified resource.'
      operationId: updateTheSpecifiedResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: non
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the region.'
        example: 3
        required: true
        schema:
          type: integer
  /api/prefixes:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store the specified resource.'
      operationId: storeTheSpecifiedResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prefix:
                  type: string
                  description: ''
                  example: omnis
              required:
                - prefix
      security: []
  '/api/prefixes/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified resource.'
      operationId: updateTheSpecifiedResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                prefix:
                  type: string
                  description: ''
                  example: tenetur
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the prefix.'
        example: 1
        required: true
        schema:
          type: integer
  /api/zip-codes:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store the specified resource.'
      operationId: storeTheSpecifiedResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: integer
                  description: 'Must be at least 3.'
                  example: 83
                city_id:
                  type: string
                  description: ''
                  example: et
              required:
                - code
                - city_id
      security: []
  '/api/zip-codes/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified resource.'
      operationId: updateTheSpecifiedResource
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: integer
                  description: 'Must be at least 3.'
                  example: 41
                city_id:
                  type: integer
                  description: ''
                  example: 5
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the zip code.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
